version: '3.8'

services:
  nginx:
    build:
     context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    restart: always

  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
        #command: ["./wait-for-it.sh", "db:3306", "--", "php", "-S", "0.0.0.0:80", "-t", "public"]
    command: ["./wait-for-it.sh", "db:3306", "--","python", "app.py"]
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=hospital_db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: hospital_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./hospital.sql:/docker-entrypoint-initdb.d/hospital.sql

volumes:
 db_data:
